### ISSUE TITLE
[疑问]关于项目算法

### ISSUE THREAD

**Issue by SuperSummer07** [SGHGZ/sgwallbackup#1]
学长好，我是水高23级的一名学生，我注意到本项目的代码经过混淆处理了。
我有浏览过sghgz.top网站的内容，对获取水高墙qq空间数据的算法有些好奇，我的猜测是爬虫，想证实一下我的想法。
如果您看到这个issue可以回复一下我吗，可以直接在github留言，或者我的邮箱：direck@foxmail.com
感激不尽

**Comment by SGHGZ** [comment]
已经邮件回复了,请查看您的邮箱
